# SPDX-License-Identifier: GPL-2.0

spinand-objs := core.o gigadevice.o macronix.o micron.o winbond.o toshiba.o zetta.o xtx.o foresee.o dosilicon.o storage_sn.o
obj-$(CONFIG_MTD_SPI_NAND) += spinand.o
